"""Semantic-class faults (PRD §12.2): `byzantine`.

**Deferred — P1, not in this build's MVP set.**

This module intentionally contains no executable fault logic. Per mission Design Constraint 7
("every §12.2 fault implemented or explicitly deferred with a reason in the NOT DONE block"),
`byzantine` is one of the six deferred types; this file is that declaration, in the location the
mission's DELIVERABLES names ("one module per fault class"), not a partial or placeholder
implementation (AGENTS.md §3 forbids stub code that pretends to function — a module with no
executable content pretends nothing).

**Why `byzantine` is deferred, not attempted.** CONTEXT.md §3 locks this build's MVP fault set to
`latency`, `agent_crash`, `message_drop`, `tool_failure` — `byzantine` (PRD §12.2, tier P1) is
outside it. Beyond the tier gate, `byzantine` has a real architectural gap distinct from the
"no interception point" gap `transport.py`/`dependency.py` document: PRD §12.2's own Safety row
requires its output come "only from a declared pool; never generated by a model" — `pool` is
already a `str` param in `scenario.schema.FAULT_CATALOGUE["byzantine"]`, but nothing in P08 or
this build defines *where* a declared pool of stale/contradictory/confident-wrong responses is
declared, loaded, or validated against (a fixture-level concept with no home yet — not
`runtime/faults/`'s to invent, per the uncertainty protocol). Attempting `byzantine` here would
mean guessing that schema too, silently, in a module the mission did not ask to extend the
scenario surface.

**Structurally unreachable, not just undocumented.** `registry.FaultRegistry.
from_resolved_scenario` raises `FaultNotImplementedError` (`E-CHAOS-002`) for any fault type
outside `registry.MVP_FAULT_TYPES` — including `byzantine` — before any per-fault-class module
(this one included) ever sees an `ArmedFault` for it. A scenario that declares a `byzantine`
fault fails at registry construction, loudly, every time; it does not silently no-op (PRD
§12.5's own warning against exactly that failure mode).

See `docs/chaos-safety.md` §"MVP fault set" for this and the other five deferred types together,
and the closing NOT DONE block for the same statement in the mission's required output shape.
"""

from __future__ import annotations

__all__: list[str] = []
