/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe (PRD Sec35)
         * @description Return `{"status": "ok"}` if the process can answer at all.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a `.agentdx` bundle (PRD §26.1)
         * @description Verify and register an uploaded `.agentdx` bundle; return its local `run_id`.
         *
         *     Raises:
         *         BundleError: `400` — `E-BUNDLE-001` verification failed · `E-BUNDLE-002` incompatible
         *             schema · `E-BUNDLE-005` unsafe archive member · `E-BUNDLE-007` a different log
         *             already exists under this `run_id` (all handled globally).
         *
         *     Depends on `get_store_async_http`, not the sync `get_store` every other route in this
         *     module uses: this is the one `async def` route here (`UploadFile.read()` is itself
         *     async), and a sync generator dependency opens its `sqlite3.Connection` in FastAPI's
         *     threadpool while an `async def` route body runs on the event loop thread — a real,
         *     empirically-confirmed cross-thread `sqlite3.ProgrammingError` (see `deps.py::
         *     get_store_async_http`'s own docstring), not a hypothetical one.
         */
        post: operations["import_run_api_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Self-observability counters, Prometheus text format (PRD Sec35)
         * @description Return the PRD Sec35 metric set as `text/plain; version=0.0.4` (Prometheus exposition).
         */
        get: operations["get_metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs (PRD §26.1)
         * @description List runs, newest first, cursor-paginated by `(created_at desc, run_id)` (PRD §26.1).
         *
         *     `Store.list_runs()` returns every run (ordered by `run_id`, not `created_at`) — there is
         *     no indexed `created_at`-ordered read to page through (extending `store/` with one is
         *     outside this prompt's `DELIVERABLES`; see `docs/api.md`). This route re-sorts in Python,
         *     which is O(run count) rather than O(page size) — acceptable for a `runs` table (hundreds
         *     to low thousands of rows in realistic local use), unlike the `events` table this same
         *     trade-off would be disqualifying for (Design Constraint 6).
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * Start a run (PRD §26.1)
         * @description Validate, check the concurrency gate, and hand off to the configured `RunLauncher`.
         *
         *     Raises:
         *         ScenarioNotFoundError / ScenarioLoadError / ScenarioValidationError: `400`-family —
         *             the scenario does not exist or does not validate.
         *         TooManyConcurrentRunsError: `409 E-RUN-409`.
         *         RunLaunchUnavailableError: `503` — no `RunLauncher` is configured on this server
         *             (CONTEXT.md §7's `RunHost` gap; see this module's docstring).
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare two runs (PRD §26.1)
         * @description Diff two runs' real, available metrics and findings.
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404` — either run.
         *         CompareIncomparableError: `400 E-CMP-001` — different scenario hashes, no `force`.
         *
         *     `metric_deltas` covers exactly the numeric fields both runs' own `RunRecord`s carry for
         *     real (`virtual_makespan_ms`, `wall_makespan_ms`, `event_count`) — not a wider metric set,
         *     because nothing in this build computes one (no `analysis.compare`/`diff` module exists;
         *     Design Constraint 1: a route needing a missing computation is a declared gap, not
         *     something to invent inline). `verdict_changed`/`verdict_a`/`verdict_b` are always
         *     `False`/`None`/`None` for the same reason `GET /runs/{id}`'s `verdict` is always `None`
         *     (P17 gap). Findings are matched across runs by `(type, subtype, severity, title)` — the
         *     two runs' `finding_id`s are independently generated and never equal, so identity here is
         *     content-based, declared as such rather than silently assumed to be `finding_id` equality.
         */
        post: operations["compare_runs_api_runs_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run metadata + verdict (PRD §26.1)
         * @description Return a run's metadata, real counts and (when computed) its verdict.
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404`.
         *
         *     `timing.critical_path_ms` is reported as `null`: computing it means building the full
         *     timing DAG (`analysis.timing.build_timing_dag` + `critical_path`), the same cost
         *     `GET .../graph` already pays where the PRD's own example payload needs the number — this
         *     endpoint does not additionally pay that cost on every call just to fill one field callers
         *     needing it can get from `.../graph` directly. `determinism.unwrapped_tools` is `0` on
         *     every run: no event or field anywhere in this codebase currently records it (grepped, not
         *     assumed) — a real, declared gap, not a fabricated zero passed off as a real count.
         */
        get: operations["get_run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated event log (PRD §26.1)
         * @description Return one page of a run's event log, streamed rather than materialised.
         *
         *     Design Constraint 6: never load a 200 000-event run into memory for one page.
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404`.
         *
         *     `next_from_seq` resumes correctly during a live run: it is the seq immediately after the
         *     last event this call *read* (matched or not), so a client that pages to the current end
         *     and asks again later picks up exactly where new events start, with no gap and no
         *     duplicate — the same cursor discipline PRD §26.2 requires of the WebSocket reconnect path.
         */
        get: operations["get_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/exploration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bounded schedule exploration results (PRD §26.1, §15.6)
         * @description Return a run's exploration `Report` (PRD §15), including the required `coverage_statement`.
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404`.
         *         NotYetAvailableError: `409` — always, in this build. `explore.report.Report` is real
         *             (P13) but `api/` may not import `agentdx.explore` (`.importlinter`
         *             `explore-below-transport-layer`: `explore/` must not import `api/`, and the
         *             converse contract, `api-never-imports-runtime`, was written before `explore/`
         *             existed and does not list it as permitted either — confirmed against the actual
         *             `.importlinter`, not assumed from the CONTEXT.md §4 table's prose). No prompt
         *             persists an exploration `Report` into the store (no table exists for one — see
         *             `docs/api.md`), so there is nothing this route can read regardless. Surfaced
         *             plainly rather than fabricated (PRD §36 rule 1).
         */
        get: operations["get_exploration_api_runs__run_id__exploration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a run as a `.agentdx` bundle (PRD §26.1)
         * @description Export a sealed run to a self-contained, self-verifying `.agentdx` bundle.
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404`.
         *         BundleError: `400` — `E-BUNDLE-004` the run has no events (handled globally).
         *
         *     Thin: `store.bundle.export_bundle` already resolves `created_at`/`scenario`/
         *     `agentdx_version` from the store when not given, so this route supplies nothing beyond
         *     `run_id` and a destination path.
         */
        get: operations["export_run_api_runs__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/faults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject a fault into a live run (PRD §26.1)
         * @description Validate and arm a fault against a running run, via the configured `FaultController`.
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404`.
         *         RunNotRunningError: `409` — the run is not `running`.
         *         UnknownFaultTypeError: `400` — not in `FAULT_CATALOGUE`, or a declared-but-unshipped
         *             P1 fault (CONTEXT.md §3: only the P0 tier executes in this build).
         *         FaultTargetNotFoundError: `400 E-FAULT-001` — only checked when the fault's
         *             `target_kinds` is unambiguously `(agent,)`, against the run's real agent roster
         *             (`store.list_agent_ids`); edge/tool/state_key/provider targets are not verified
         *             (declared gap — this build has no cheap way to enumerate them without a graph
         *             resolution `api/` cannot perform, see this module's docstring).
         *         ChaosAuthorizationError: `403 E-CHAOS-001` — I12/§13.3.
         *         FaultControlUnavailableError: `503` — no `FaultController` configured.
         */
        post: operations["inject_fault_api_runs__run_id__faults_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Findings (PRD §26.1)
         * @description Return a run's findings, severity/type-filtered, precomputed (PRD §26.1, §26.3).
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404`.
         */
        get: operations["get_findings_api_runs__run_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Node/edge graph (PRD §26.1)
         * @description Return nodes, edges and the critical path, computed live from the sealed event log.
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404`.
         *         TimingAnalysisError / OverheadAnalysisError: `409` — the log is not yet in a shape
         *             this analysis can run over (PRD §36 `E-ANLZ-*`; most commonly, the run has not
         *             been sealed and still has an open span).
         *
         *     `at_virtual_ts`, when given, restricts the *reported* nodes/edges to ones whose own
         *     activity had started by that instant; the critical path and `cp_share`/`cp_ms` figures
         *     are still computed over the *full* sealed run and only filtered to the surviving node
         *     ids — this is a simplification of PRD §26.1's "graph state as of that instant", declared
         *     in `docs/api.md`, not a full historical re-derivation of what the critical path *would
         *     have been* had the run stopped at that instant.
         */
        get: operations["get_graph_api_runs__run_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/scorecard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scorecard (PRD §26.1)
         * @description Return a run's persisted scorecard.
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404`.
         *         NotYetAvailableError: `409` `E-SCORE-001` — the run exists but no scorecard has been
         *             computed and persisted for it yet. No prompt in this build runs the full
         *             `baseline -> verdict` pipeline and calls `store.upsert_scorecard` (P17, not
         *             started) — see `docs/api.md`. Reported plainly, not as an empty `200` (PRD §36
         *             rule 1) and not as `404` (the run itself is real; its scorecard is what's missing).
         */
        get: operations["get_scorecard_api_runs__run_id__scorecard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reconstructed state (PRD §26.1, §20.4)
         * @description Return every state key's last-known value hash as of `at_virtual_ts` (PRD §20.4).
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404`.
         */
        get: operations["get_state_at_api_runs__run_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/waterfall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Span waterfall (PRD §26.1)
         * @description Return per-agent lanes of spans with virtual start/end and critical-path flags.
         *
         *     Raises:
         *         RunNotFoundError: `E-RUN-404`.
         *         TimingAnalysisError: `409` — see `get_graph`.
         *
         *     `bucket` (PRD §16.2.2's six-way overhead classification) is reported as `null` on every
         *     span: `analysis.overhead` computes and aggregates bucket *totals*
         *     (`OverheadDecomposition.bucket_ms`) but exposes no public per-node classification to
         *     project back onto an individual span — only its private `_classify_node` does, and this
         *     layer does not reach into another module's private surface. This is a real, declared
         *     gap (`docs/api.md` "What GET .../waterfall does not yet do"), not a silent omission.
         */
        get: operations["get_waterfall_api_runs__run_id__waterfall_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List scenarios (PRD Sec26.1)
         * @description Return every scenario the store has persisted, unioned with `scenarios_dir`'s files.
         *
         *     A scenario id present in both sources is reported once, from the store — the store's
         *     copy is the one a real run's `runs.scenario_hash` actually pins (PRD Sec27.2), so it is the
         *     more authoritative of the two for an id that exists in both places.
         */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry-run validate a scenario (PRD Sec26.1)
         * @description Validate scenario text or an existing scenario id and return the resolved document.
         *
         *     Never raises for an invalid scenario (Design Constraint 1's "thin" still holds: this
         *     calls `scenario.loader`/`scenario.validate` and serialises, no rule lives here) — a
         *     malformed or invalid scenario is a `200` with `valid: false`, because that is what makes
         *     this endpoint safe for the UI's chaos panel to call on every keystroke.
         *
         *     Raises:
         *         ScenarioNotFoundError: `scenario_id` was given and names nothing in either source.
         */
        post: operations["validate_scenario_api_scenarios_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a scenario (PRD Sec26.1)
         * @description Return one scenario's raw content plus its resolved (defaults-applied) form.
         *
         *     Raises:
         *         ScenarioNotFoundError: `E-SCEN-404` — neither source has this id.
         */
        get: operations["get_scenario_api_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AgentDX version and event schema version (PRD Sec35)
         * @description Return the AgentDX package version and the event `schema_version` it writes.
         */
        get: operations["get_version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
/**
 * Named aliases for the (self-referential) JsonValue-Input/Output schemas — patched in by
 * scripts/patch-schema-jsonvalue.mjs, see CONTEXT.md ADR-016. Same recursive union
 * openapi-typescript generated from the real OpenAPI schema, just addressable by name instead
 * of by bracketed index, which is the part TypeScript can check (TS2502 workaround).
 */
type JsonValueInput = string | number | boolean | JsonValueInput[] | { [key: string]: JsonValueInput } | null;
type JsonValueOutput = string | number | boolean | JsonValueOutput[] | { [key: string]: JsonValueOutput } | null;

export interface components {
    schemas: {
        /** Body_import_run_api_import_post */
        Body_import_run_api_import_post: {
            /** File */
            file: string;
        };
        /**
         * CompareRequest
         * @description `POST /api/runs/compare` request body (PRD §26.1, `[SOURCE]`).
         */
        CompareRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Run A */
            run_a: string;
            /** Run B */
            run_b: string;
        };
        /**
         * CompareResponse
         * @description `POST /api/runs/compare` response: metric deltas, finding diff, verdict change.
         */
        CompareResponse: {
            /** Findings Added */
            findings_added: components["schemas"]["FindingOut"][];
            /** Findings Removed */
            findings_removed: components["schemas"]["FindingOut"][];
            /** Findings Unchanged */
            findings_unchanged: components["schemas"]["FindingOut"][];
            /** Metric Deltas */
            metric_deltas: components["schemas"]["MetricDelta"][];
            /** Run A */
            run_a: string;
            /** Run B */
            run_b: string;
            /** Verdict A */
            verdict_a: string | null;
            /** Verdict B */
            verdict_b: string | null;
            /** Verdict Changed */
            verdict_changed: boolean;
        };
        /**
         * CountsSummary
         * @description Real per-run counts: events, spans, messages, LLM calls and tokens.
         */
        CountsSummary: {
            /** Events */
            events: number;
            /** Llm Calls */
            llm_calls: number;
            /** Messages */
            messages: number;
            /** Spans */
            spans: number;
            /** Tokens */
            tokens: number;
        };
        /**
         * DeterminismSummary
         * @description A run's determinism health: canonical log hash and warning counts.
         */
        DeterminismSummary: {
            /** Canonical Log Hash */
            canonical_log_hash: string | null;
            /** Nondeterminism Warnings */
            nondeterminism_warnings: number;
            /** Unwrapped Tools */
            unwrapped_tools: number;
        };
        /**
         * EventOut
         * @description One event, exactly as `events.canonical.encode_event` serialises it.
         */
        EventOut: {
            /** Agent Id */
            agent_id?: string | null;
            /** Causal Parents */
            causal_parents: number[];
            /** Clock Slot */
            clock_slot?: string | null;
            /** Fault Id */
            fault_id?: string | null;
            /** Payload */
            payload: {
                [key: string]: JsonValueOutput;
            };
            /** Run Id */
            run_id: string;
            /** Sched Step */
            sched_step: number;
            /** Schema Version */
            schema_version: number;
            /** Seq */
            seq: number;
            /** Span Id */
            span_id?: string | null;
            /** Type */
            type: string;
            /** Vclock */
            vclock: {
                [key: string]: number;
            };
            /** Virtual Ts Ms */
            virtual_ts_ms: number;
            /** Wall Ts Ms */
            wall_ts_ms: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * EventsPageResponse
         * @description `GET /api/runs/{id}/events` response — one page, cursor and total.
         */
        EventsPageResponse: {
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Next From Seq */
            next_from_seq: number | null;
            /** Total */
            total: number;
        };
        /**
         * Evidence
         * @description `analysis.verdict.Evidence`, projected (PRD §18.4) — I6: `event_seqs` non-empty.
         */
        Evidence: {
            /** Computation */
            computation: string;
            /** Event Seqs */
            event_seqs: number[];
            /** Span Ids */
            span_ids: string[];
        };
        /**
         * ExplorationResponse
         * @description PRD §26.1 / §15.6. `coverage_statement` is I10's required, verbatim field.
         */
        ExplorationResponse: {
            /** Capped */
            capped: boolean;
            /** Coverage Statement */
            coverage_statement: string;
            /** K */
            k: number;
            /** New Findings */
            new_findings: components["schemas"]["FindingOut"][];
            /** Reduced Away */
            reduced_away: number;
            /** Schedules Executed */
            schedules_executed: number;
            /** Unique Schedules */
            unique_schedules: number;
        };
        /**
         * ExploreOptions
         * @description PRD §26.1 `POST /api/runs` request body's `explore` object.
         */
        ExploreOptions: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
        };
        /**
         * FaultInjectRequest
         * @description `POST /api/runs/{id}/faults` request body (PRD §26.1, `[SOURCE]`).
         */
        FaultInjectRequest: {
            /** Params */
            params?: {
                [key: string]: JsonValueInput;
            };
            /** Target */
            target: string;
            trigger?: components["schemas"]["FaultTrigger"];
            /** Type */
            type: string;
        };
        /**
         * FaultInjectResponse
         * @description `202` response of `POST /api/runs/{id}/faults`.
         */
        FaultInjectResponse: {
            /** Armed At Virtual Ts */
            armed_at_virtual_ts: number;
            /** Fault Id */
            fault_id: string;
        };
        /**
         * FaultTrigger
         * @description The `trigger` object of a `POST /api/runs/{id}/faults` request body.
         */
        FaultTrigger: {
            /**
             * Immediate
             * @default false
             */
            immediate: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * FindingOut
         * @description `store.FindingRecord`, projected.
         */
        FindingOut: {
            /** Description */
            description: string;
            /** Evidence */
            evidence: {
                [key: string]: JsonValueOutput;
            };
            /** Id */
            id: string;
            /** Recommendation */
            recommendation: string | null;
            /** Repro Scenario */
            repro_scenario: string | null;
            /** Severity */
            severity: string;
            /** Subtype */
            subtype: string | null;
            /** Suppressed By */
            suppressed_by: string | null;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /**
         * FindingsResponse
         * @description `GET /api/runs/{id}/findings` response — one run's findings, filtered.
         */
        FindingsResponse: {
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
        };
        /**
         * GraphEdge
         * @description One agent-pair edge of `GET /api/runs/{id}/graph` (PRD §26.1).
         */
        GraphEdge: {
            /** Cp Handoff Ms */
            cp_handoff_ms: number;
            /** Cp Share */
            cp_share: number;
            /** From */
            from: string;
            /** Messages */
            messages: number;
            /** On Critical Path */
            on_critical_path: boolean;
            /** To */
            to: string;
            /** Total Handoff Ms */
            total_handoff_ms: number;
        };
        /**
         * GraphNode
         * @description One agent node of `GET /api/runs/{id}/graph` (PRD §26.1).
         */
        GraphNode: {
            /** Busy Ms */
            busy_ms: number;
            /** Cp Ms */
            cp_ms: number;
            /** Id */
            id: string;
            /** Idle Ms */
            idle_ms: number;
            /** Role */
            role: string | null;
            /** Status */
            status: string;
            /** Tokens */
            tokens: number;
        };
        /**
         * GraphRef
         * @description A run's graph identity — content hash plus the observed agent roster.
         */
        GraphRef: {
            /** Agents */
            agents: string[];
            /** Hash */
            hash: string;
        };
        /**
         * GraphResponse
         * @description `GET /api/runs/{id}/graph` response: nodes, edges and the critical path.
         */
        GraphResponse: {
            /** Critical Path */
            critical_path: string[];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description `GET /api/health` response (PRD §35).
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * ImportResponse
         * @description `POST /api/import` response: the newly assigned local `run_id`.
         */
        ImportResponse: {
            /** Run Id */
            run_id: string;
        };
        "JsonValue-Input": JsonValueInput;
        "JsonValue-Output": JsonValueOutput;
        /**
         * Metric
         * @description `analysis.verdict.Metric`, projected (PRD §18.4).
         */
        Metric: {
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /**
         * MetricDelta
         * @description One metric's value in each run plus the difference between them.
         */
        MetricDelta: {
            /** Delta */
            delta: number | null;
            /** Name */
            name: string;
            /** Run A */
            run_a: number | null;
            /** Run B */
            run_b: number | null;
        };
        /**
         * Recommendation
         * @description One `analysis.verdict.Recommendation`, projected (PRD §18.4).
         */
        Recommendation: {
            evidence: components["schemas"]["Evidence"];
            /** Text */
            text: string;
            /** Trigger */
            trigger: string;
        };
        /**
         * RunCreateRequest
         * @description `POST /api/runs` request body (PRD §26.1, `[SOURCE]`).
         */
        RunCreateRequest: {
            explore?: components["schemas"]["ExploreOptions"];
            /**
             * Mode
             * @enum {string}
             */
            mode: "baseline" | "chaos" | "replay";
            /** Scenario Id */
            scenario_id: string;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /**
         * RunCreateResponse
         * @description `202` response of `POST /api/runs`.
         */
        RunCreateResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Ws */
            ws: string;
        };
        /**
         * RunDetail
         * @description `GET /api/runs/{id}` response (PRD §26.1, `[SOURCE]`).
         *
         *     `verdict` is `None` until the run's scorecard has been computed and persisted — no
         *     prompt in this build yet runs the full `timing -> overhead -> redundancy -> race ->
         *     baseline -> resilience -> verdict` pipeline and calls `store.upsert_scorecard` (P17,
         *     not started; see `docs/api.md` "What this endpoint does not yet do"). This is reported
         *     as `null`, not fabricated and not a 404 — PRD §36 rule 2, "partial results beat no
         *     results": the run's own metadata is always real, even when its verdict is not yet in.
         */
        RunDetail: {
            /** Baseline Run Id */
            baseline_run_id: string | null;
            /** Comparability */
            comparability: string | null;
            counts: components["schemas"]["CountsSummary"];
            determinism: components["schemas"]["DeterminismSummary"];
            graph: components["schemas"]["GraphRef"];
            /** Mode */
            mode: string;
            /** Run Id */
            run_id: string;
            scenario: components["schemas"]["ScenarioRef"];
            /** Seed */
            seed: number;
            /** Status */
            status: string;
            timing: components["schemas"]["TimingSummary"];
            verdict: components["schemas"]["VerdictOut"] | null;
        };
        /**
         * RunListResponse
         * @description `GET /api/runs` response.
         */
        RunListResponse: {
            /** Next Cursor */
            next_cursor?: string | null;
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /**
         * RunSummary
         * @description One row of `GET /api/runs`'s `runs` array — `RunRecord`, projected.
         */
        RunSummary: {
            /** Baseline Of */
            baseline_of: string | null;
            /** Created At */
            created_at: string;
            /** Event Count */
            event_count: number | null;
            /** Mode */
            mode: string;
            /** Replay Of */
            replay_of: string | null;
            /** Run Id */
            run_id: string;
            /** Scenario Id */
            scenario_id: string | null;
            /** Sealed At */
            sealed_at: string | null;
            /** Seed */
            seed: number;
            /** Status */
            status: string;
            /** Virtual Makespan Ms */
            virtual_makespan_ms: number | null;
            /** Wall Makespan Ms */
            wall_makespan_ms: number | null;
        };
        /**
         * ScenarioDetail
         * @description `GET /api/scenarios/{id}` response: raw content plus its resolved form.
         */
        ScenarioDetail: {
            /** Content */
            content: string;
            /** Content Hash */
            content_hash: string | null;
            /** Path */
            path: string | null;
            /** Resolved */
            resolved: {
                [key: string]: JsonValueOutput;
            };
            /** Scenario Id */
            scenario_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "store" | "file";
        };
        /**
         * ScenarioListResponse
         * @description `GET /api/scenarios` response.
         */
        ScenarioListResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioSummary"][];
        };
        /**
         * ScenarioRef
         * @description Which scenario a run used — id (if known) plus its resolved content hash.
         */
        ScenarioRef: {
            /** Hash */
            hash: string;
            /** Id */
            id: string | null;
        };
        /**
         * ScenarioSummary
         * @description One row of `GET /api/scenarios`'s listing — store- or file-sourced.
         */
        ScenarioSummary: {
            /** Path */
            path: string | null;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "store" | "file";
            /** Version */
            version: number | null;
        };
        /**
         * ScenarioValidateRequest
         * @description `POST /api/scenarios/validate` request body.
         *
         *     Exactly one of `text` (raw YAML, e.g. from the UI's chaos panel) or `scenario_id` (an
         *     already-known scenario, from the store or `scenarios_dir`) must be given.
         */
        ScenarioValidateRequest: {
            /** Scenario Id */
            scenario_id?: string | null;
            /**
             * Source Name
             * @default <scenario>
             */
            source_name: string;
            /** Text */
            text?: string | null;
        };
        /**
         * ScenarioValidateResponse
         * @description `POST /api/scenarios/validate` response — always `200`, see the route's docstring.
         */
        ScenarioValidateResponse: {
            /** Errors */
            errors: components["schemas"]["ScenarioValidationErrorOut"][];
            /** Resolved */
            resolved: {
                [key: string]: JsonValueOutput;
            } | null;
            /** Valid */
            valid: boolean;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /**
         * ScenarioValidationErrorOut
         * @description One `scenario.validate.ScenarioError`, projected.
         */
        ScenarioValidationErrorOut: {
            /** Code */
            code: string;
            /** Docs */
            docs: string;
            /** File */
            file: string | null;
            /** Line */
            line: number | null;
            /** Message */
            message: string;
            /** Path */
            path: string;
            /** Suggestion */
            suggestion: string;
        };
        /**
         * ScorecardResponse
         * @description PRD §17.4's structure, as persisted (`store.ScorecardRecord.payload`).
         *
         *     Passed through unreshaped: the route serialises what the analysis pipeline wrote, and
         *     inventing a stricter schema here would be a second, competing opinion of what a
         *     scorecard contains.
         */
        ScorecardResponse: {
            [key: string]: unknown;
        };
        /**
         * StateKey
         * @description One state key's reconstructed value as of a virtual timestamp (PRD §20.4).
         */
        StateKey: {
            /** Key */
            key: string;
            /** Size Bytes */
            size_bytes?: number | null;
            value?: JsonValueOutput;
            /** Value Hash */
            value_hash: string;
            /** Writer */
            writer: string | null;
            /** Written At Seq */
            written_at_seq: number;
        };
        /**
         * StateResponse
         * @description `GET /api/runs/{id}/state` response.
         */
        StateResponse: {
            /** At Seq */
            at_seq: number | null;
            /** At Virtual Ts */
            at_virtual_ts: number;
            /** Keys */
            keys: components["schemas"]["StateKey"][];
        };
        /**
         * TimingSummary
         * @description Makespan figures for `GET /runs/{id}` — virtual, wall and critical-path ms.
         */
        TimingSummary: {
            /** Critical Path Ms */
            critical_path_ms: number | null;
            /** Virtual Makespan Ms */
            virtual_makespan_ms: number | null;
            /** Wall Makespan Ms */
            wall_makespan_ms: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerdictFinding
         * @description One finding cited by a `Verdict` (PRD §18.4), projected.
         */
        VerdictFinding: {
            /** Claim */
            claim: string;
            /** Confidence */
            confidence: string;
            evidence: components["schemas"]["Evidence"];
            /** Finding Id */
            finding_id: string;
            metric: components["schemas"]["Metric"];
            /** Severity */
            severity: string;
            /** Type */
            type: string;
        };
        /**
         * VerdictOut
         * @description `analysis.verdict.Verdict`, projected — `GET /runs/{id}`'s `verdict` object (PRD §18).
         */
        VerdictOut: {
            /** Class */
            class: string;
            /** Confidence */
            confidence: string;
            /** Coordination Score */
            coordination_score: number | null;
            evidence: components["schemas"]["Evidence"];
            /** Findings */
            findings: components["schemas"]["VerdictFinding"][];
            /** Headline */
            headline: string;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /** Secondary Classes */
            secondary_classes: string[];
        };
        /**
         * VersionResponse
         * @description `GET /api/version` response: package version plus event schema version.
         */
        VersionResponse: {
            /** Schema Version */
            schema_version: number;
            /** Version */
            version: string;
        };
        /**
         * WaterfallLane
         * @description One agent's lane of spans in a `GET /api/runs/{id}/waterfall` response.
         */
        WaterfallLane: {
            /** Agent */
            agent: string;
            /** Spans */
            spans: components["schemas"]["WaterfallSpan"][];
        };
        /**
         * WaterfallResponse
         * @description `GET /api/runs/{id}/waterfall` response: makespans plus every lane.
         */
        WaterfallResponse: {
            /** Baseline Makespan Ms */
            baseline_makespan_ms: number | null;
            /** Lanes */
            lanes: components["schemas"]["WaterfallLane"][];
            /** Virtual Makespan Ms */
            virtual_makespan_ms: number;
        };
        /**
         * WaterfallSpan
         * @description One span row of `GET /api/runs/{id}/waterfall` (PRD §26.1).
         */
        WaterfallSpan: {
            /** Bucket */
            bucket: string | null;
            /** End Ms */
            end_ms: number;
            /** Fault Id */
            fault_id: string | null;
            /** Kind */
            kind: string;
            /** Name */
            name: string | null;
            /** On Critical Path */
            on_critical_path: boolean;
            /** Seq End */
            seq_end: number;
            /** Seq Start */
            seq_start: number;
            /** Span Id */
            span_id: string;
            /** Start Ms */
            start_ms: number;
            /** Status */
            status: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    import_run_api_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_run_api_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                /** @description Filter: exact status match. */
                status?: string | null;
                /** @description Filter: True for fixture-targeted runs, False for user-graph runs. */
                fixture?: boolean | null;
                /** @description Page size. */
                limit?: number | null;
                /** @description Opaque `created_at|run_id` cursor. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_runs_api_runs_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                /** @description First seq to include, inclusive. */
                from_seq?: number;
                /** @description Page size, capped at the server max. */
                limit?: number | null;
                /** @description Comma-separated `EventType` values. */
                types?: string | null;
                /** @description Filter: exact `agent_id` match. */
                agent?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exploration_api_runs__run_id__exploration_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplorationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_api_runs__run_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inject_fault_api_runs__run_id__faults_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaultInjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultInjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_findings_api_runs__run_id__findings_get: {
        parameters: {
            query?: {
                /** @description Filter: exact severity match. */
                severity?: string | null;
                /** @description Filter: exact type match. */
                type?: string | null;
                /** @description Include findings a guard suppressed. */
                include_suppressed?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_runs__run_id__graph_get: {
        parameters: {
            query?: {
                /** @description Restrict to nodes that had started by this virtual ms (PRD §26.1). */
                at_virtual_ts?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scorecard_api_runs__run_id__scorecard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScorecardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_at_api_runs__run_id__state_get: {
        parameters: {
            query: {
                /** @description Reconstruct state as of this virtual ms. */
                at_virtual_ts: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_waterfall_api_runs__run_id__waterfall_get: {
        parameters: {
            query?: {
                /** @description Window start, virtual ms. */
                from_ms?: number | null;
                /** @description Window end, virtual ms. */
                to_ms?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterfallResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
        };
    };
    validate_scenario_api_scenarios_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_api_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
